import React, { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Share2,
  FileText,
  Link,
  Sparkles,
  Award,
  Terminal
} from 'lucide-react';

export function ShareExportModal({ data, onClose }) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  const { username, userProfile, overview, score, aiAnalysis, techStack } = data;
  const shareUrl = `${window.location.origin}/u/${encodeURIComponent(username)}`;

  const markdownProfile = `### 🧑‍💻 Developer Profile: ${userProfile.name || username} (@${username})
> *Generated by GitHub Profile Analyzer with AI Evaluation*

- **Archetype**: ${aiAnalysis.archetype} (${aiAnalysis.estimatedLevel} - AI Estimated)
- **GitHub Developer Score**: ${score.totalScore}/100 (${score.tier})
- **Top Languages**: ${techStack.primaryStack.slice(0, 5).join(', ')}
- **Public Repositories**: ${overview.originalReposCount} original (${overview.totalStars}★ earned)

#### 📝 Summary
${aiAnalysis.summary}

#### ⚡ Strongest Skills & Strengths
${aiAnalysis.strengths.map(s => `- ${s}`).join('\n')}

#### 🎯 Growth Areas
${aiAnalysis.improvementAreas.map(a => `- ${a}`).join('\n')}

---
*Report Link:* ${shareUrl}
`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2500);
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownProfile);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-github-dark border border-github-border rounded-2xl max-w-xl w-full shadow-2xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-github-border flex items-center justify-between bg-github-darkest/50">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-github-accent/10 border border-github-accent/20 flex items-center justify-center text-github-accent">
              <Share2 className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                Share & Export Profile
              </h3>
              <p className="text-xs text-github-textMuted font-mono">
                @{username} developer analysis
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-github-textMuted hover:text-white p-1 rounded-lg hover:bg-github-card transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-5 text-xs">
          {/* Shareable Link Box */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-white font-mono flex items-center gap-1.5">
              <Link className="w-3.5 h-3.5 text-github-accent" />
              <span>Shareable Report URL</span>
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                readOnly
                value={shareUrl}
                className="flex-1 px-3 py-2 bg-github-darkest border border-github-border rounded-xl text-github-textPrimary font-mono text-xs focus:outline-none select-all"
              />
              <button
                onClick={handleCopyLink}
                className="flex items-center gap-1.5 px-3.5 py-2 bg-github-accent hover:bg-github-accentHover text-github-darkest font-semibold rounded-xl transition-all flex-shrink-0"
              >
                {copiedLink ? <Check className="w-4 h-4 text-emerald-900" /> : <Copy className="w-4 h-4" />}
                <span>{copiedLink ? 'Copied!' : 'Copy Link'}</span>
              </button>
            </div>
          </div>

          {/* Markdown Resume / Portfolio Summary */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-white font-mono flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5 text-github-purpleLight" />
                <span>Generated Markdown Profile</span>
              </label>
              <button
                onClick={handleCopyMarkdown}
                className="flex items-center gap-1 text-[11px] font-mono text-github-accent hover:underline"
              >
                {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-github-greenText" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedMarkdown ? 'Profile Copied to Clipboard!' : 'Copy Profile Markdown'}</span>
              </button>
            </div>

            <div className="p-3.5 rounded-xl bg-github-darkest border border-github-border font-mono text-[11px] text-github-textMuted max-h-48 overflow-y-auto whitespace-pre-wrap leading-relaxed select-all">
              {markdownProfile}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-github-border bg-github-darkest/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-github-dark hover:bg-github-card border border-github-border text-xs font-semibold text-github-textPrimary transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
